version: "3"
services:
  backendservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    # volumes:
    #   - "./:/usr/src/app"
    depends_on:
      - mongodbservice
  mongodbservice:
    image: "mongo:latest"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

